name: TemplateCoinSystemAPI
version: '1.0'
main: de.huntertagog.locobrokoi.TemplateCoinSystemAPI
api-version: '1.20'
depend: [CoinSystem]
commands:
  coins:
    description: Get your Coins from API
    usage: /coins
    permission: coinsystem.use
    default: op
